### ISSUE TITLE
Facing error in installation

### ISSUE THREAD

**Issue by vnrajan** [GiacomoLaw/Keylogger#58]
Hi,

I am facing below error while installing the keylogger service. It would be grateful to receive any feedback to resolve this problem. Thanks in advance.

[root Fri Sep 28 05:13:52] # python --version
Python 2.7.6
[root Fri Sep 28 05:13:59] # pylogger_file="/home/ssseng/keylogger/Keylogger/linux/file1.log"
[root Fri Sep 28 05:14:09] # pylogger_clean=1
[root Fri Sep 28 05:14:17] # pylogger_cancel="!" 
[root Fri Sep 28 05:14:35] # python keylogger.py
<class 'Xlib.protocol.request.QueryExtension'>
<class 'Xlib.protocol.request.QueryExtension'>
RECORD extension version 1.13

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/ssseng/keylogger/Keylogger/linux-logger/pyxhook.py", line 147, in run
    self.record_dpy.record_enable_context(self.ctx, self.processevents)
  File "/usr/lib/python2.7/dist-packages/Xlib/ext/record.py", line 238, in enable_context
    context = context)
  File "/usr/lib/python2.7/dist-packages/Xlib/ext/record.py", line 215, in __init__
    rq.ReplyRequest.__init__(self, *args, **keys)
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/rq.py", line 1478, in __init__
    self.reply()
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/rq.py", line 1490, in reply
    self._display.send_and_recv(request = self._serial)
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 556, in send_and_recv
    gotreq = self.parse_response(request)
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 643, in parse_response
    gotreq = self.parse_request_response(request) or gotreq
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 729, in parse_request_response
    req._parse_response(self.data_recv[:self.request_length])
  File "/usr/lib/python2.7/dist-packages/Xlib/ext/record.py", line 219, in _parse_response
    self._callback(r)
  File "/home/ssseng/keylogger/Keylogger/linux-logger/pyxhook.py", line 199, in processevents
    self.KeyDown(hookevent)
  File "keylogger.py", line 31, in OnKeyPress
    with open(log_file, 'a') as f:
IOError: [Errno 2] No such file or directory: '/root/Desktop/file.log'

**Comment by ivanovishado** [comment]
Try to set your env variables like this:
`export VARNAME="value"`
